name: Generated Workflow
on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test task
        shell: bash
        run: echo 'test generated file version 14'