name: Generated Workflow
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test task
        shell: bash
        run: echo 'test generated file'