name: 'Delete branch from another repo'
description: 'Used for delete the generated workflow from another repository'
inputs:
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_branch:
    description: 'Destination branch for the file'
    required: false
  user_email:
    description: 'User email for GitHub'
    required: false
  user_name:
    description: 'User name for GitHub'
    required: false
  api_token:
    description: 'API token for GitHub'
    required: false
runs:
  using: "composite"
  steps:
    - name: Delete branch
      shell: bash
      run: ${{github.action_path}}/entrypoint.sh
      env:
        destination_repo: ${{ inputs.destination_repo }}
        destination_branch: ${{ inputs.destination_branch }}
        user_email: ${{ inputs.user_email }}
        user_name: ${{ inputs.user_name }}
        api_token: ${{ inputs.api_token }}
        
branding:
  icon: 'git-commit'
  color: 'green'