outputs:
  value: ${{ '$' }}{{ toJSON(steps.run.outputs) }}
runs:
  using: composite
  steps:
  - name: customDynamicAction
    shell: bash
    run: echo action 2 - ${{ github.event.repository.updated_at}}