name: 'Publish workflow to another repo'
description: 'Used for pushing a the generated workflow to another repository'
inputs:
  source_files_pattern:
    description: 'Source file pattern'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_branch:
    description: 'Destination branch for the file'
    required: false
  commit_message:
    description: 'Commit message for GitHub'
    required: false
  user_email:
    description: 'User email for GitHub'
    required: false
  user_name:
    description: 'User name for GitHub'
    required: false
runs:
  using: "composite"
  steps:
    - name: Push file
      shell: bash
      run: ${{github.action_path}}/entrypoint.sh
      args:
        - ${{ inputs.source-files-pattern }}
        - ${{ inputs.user-email }}
        - ${{ inputs.destination-branch }}
        - ${{ inputs.commit-message }}
branding:
  icon: 'git-commit'
  color: 'green'