name: Dynamic Sub-Workflow
on:
  workflow_dispatch:
  push:
    branches: [ "PublishWorkflow" ] 
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Workflow
        uses: ./.github/actions/PublishWorkflow
        with:
          source_files_pattern: 'generated.yml'
          destination_repo: 'ahmedhassan16/artifacts'
          commit_message: 'A custom message for the commit'
          api_token: ${{ secrets.PAT_TOKEN }}


  call-dynamic-workflow:
    - name: Setup1
      shell: bash
        run: |
          mkdir -p ./.dynamic-action1-uses &&
          cat <<'DYNAMIC_USES_EOF' >./.dynamic-action1-uses/action.yml
          runs:
            using: composite
            steps:
              - uses: ahmedhassan16/artifacts/.github/workflows/generated.yml@${{"workflows/$GITHUB_SHA"}}
          DYNAMIC_USES_EOF
    - name: action1
      uses: ./.dynamic-action1-uses
    

  #   with:
  # config-path: .github/labeler.yml
  #   secrets: inherit  






      # - uses: actions/checkout@v2
      #   with:
      #     repository: ahmedhassan16/artifacts
      #     path: artifacts



      
      # - name: Pushes test file
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
      #   with:
      #     source_file: 'repo/sample.jpeg'
      #     user_email: 'ah.mahmoudhassan@gmail.com'
      #     user_name: 'ahmedhassan16'
      #     destination_repo: 'ahmedhassan16/artifacts'
      #     destination_branch_create: workflows/id1
      #     commit_message: 'A custom message for the commit'
      




      # - name: Commit Generated File
      #   shell: bash
      #   run: |
          
      #     cp repo/*.*  artifacts
      #     ls artifacts
      #     cd artifacts
      #     git config user.name "ahmedhassan16"
      #     git config user.email "ah.mahmoudhassan@gmail.com"
          
      #     git add -A
      #     timestamp=$(date -u)
      #     git commit -m "Latest data: ${timestamp}" || exit 0

      #     PAT=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
      #     REPO_URL=https://github.com/ahmedhassan16/artifacts.git

      #     git config credential.helper "store --file=.git/credentials"
      #     echo "https://$PAT:x-oauth-basic@github.com" >> .git/credentials

      #     git remote add target $REPO_URL
      #     git push target HEAD:main
      
      # - name: Commit Generated File
      #   shell: bash
      #   run: |
      #     cp repo/*.*  artifacts
      #     ls artifacts

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: 'Add the very useful text file'
      #     # new_branch: custom-new-branch
      #     github_token: ${{ secrets.PAT_TOKEN }}
      #     add: 'sample.jpeg'
      #     cwd: './artifacts/' 