name: Dynamic Sub-Workflow
on:
  push:
    branches: [ "PublishWorkflow" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - uses: actions/checkout@v3
        with:
          repository: ahmedhassan16/artifacts
          path: artifacts

      - name: Publish Workflow
        uses: ./repo/.github/actions/PublishWorkflow
      
      - name: Commit Generated File
        shell: bash
        run: cp repo/*.*  artifacts

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add the very useful text file'
          new_branch: custom-new-branch
          add: 'sample.jpeg'
          cwd: './artifacts/'