name: Dynamic Trigger Workflow 
on:
  push:
    branches: [ "PublishWorkflow" ] 
  workflow_dispatch:
    branches:
      - PublishWorkflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Workflow
        uses: ./.github/actions/PublishWorkflow
        with:
          source_files_pattern: 'generated.yml'
          destination_repo: 'ahmedhassan16/artifacts'
          commit_message: 'A custom message for the commit'
          api_token: ${{ secrets.PAT_TOKEN }}

  call-dynamic-workflow: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Workflow
        uses: ./.github/actions/TriggerWorkflow
        with:
          workflow_file: 'generated.yml'
          destination_repo: 'ahmedhassan16/artifacts'
          api_token: ${{ secrets.PAT_TOKEN }}
         
  clean:
    needs: call-dynamic-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete branch
        uses: ./.github/actions/DeleteBranch
        with:
          destination_repo: 'ahmedhassan16/artifacts'
          api_token: ${{ secrets.PAT_TOKEN }}