name: Dynamic Sub-Workflow
on:
  workflow_dispatch:
  push:
    branches: [ "PublishWorkflow" ] 
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - uses: actions/checkout@v2
        with:
          repository: ahmedhassan16/artifacts
          path: artifacts

      - name: Publish Workflow
        uses: ./repo/.github/actions/PublishWorkflow
      
      - name: Commit Generated File
        shell: bash
        run: |
          
          cp repo/*.*  artifacts
          ls artifacts
          cd artifacts
          git config user.name "ahmedhassan16"
          git config user.email "ah.mahmoudhassan@gmail.com"
          
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0

          PAT=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
          REPO_URL=https://github.com/ahmedhassan16/artifacts.git

          git config credential.helper "store --file=.git/credentials"
          echo "https://$PAT:x-oauth-basic@github.com" >> .git/credentials

          git remote add target $REPO_URL
          git push target HEAD:main
      

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: 'Add the very useful text file'
      #     # new_branch: custom-new-branch
      #     add: 'sample.jpeg'
      #     cwd: './artifacts/' 