name: Dynamic Sub-Workflow
on:
  workflow_dispatch:
  push:
    branches: [ "PublishWorkflow" ] 
  permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - uses: actions/checkout@v2
        with:
          repository: ahmedhassan16/artifacts
          persist-credentials: true
          path: artifacts

      - name: Publish Workflow
        uses: ./repo/.github/actions/PublishWorkflow
      
      - name: Commit Generated File
        shell: bash
        run: |
          cp repo/*.*  artifacts
          ls artifacts

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add the very useful text file'
          # new_branch: custom-new-branch
          add: 'sample.jpeg'
          cwd: './artifacts/' 