name: Dynamic Sub-Workflow
on:
  push:
    branches: [ "PublishWorkflow" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ahmedhassan16/artifacts

      - name: Publish Workflow
        uses: ./.github/actions/PublishWorkflow