name: Dynamic Trigger Workflow 
on:
  # push:
  #   branches: [ "PublishWorkflow" ] 
  workflow_dispatch:
    branches:
      - PublishWorkflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish Workflow
        uses: ./.github/actions/PublishWorkflow
        with:
          source_files_pattern: 'generated.yml'
          destination_repo: 'ahmedhassan16/artifacts'
          commit_message: 'A custom message for the commit'
          api_token: ${{ secrets.PAT_TOKEN }}
          repo_tag: latest


  call-dynamic-workflow: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Workflow
        shell: bash
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/ahmedhassan16/artifacts/actions/workflows/generated.yml/dispatches" \
          -d '{"ref":"workflows/${{ github.sha }}/${{ github.run_id }}"}'

          sleep 10

          workflow_run_id=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          "https://api.github.com/repos/ahmedhassan16/artifacts/actions/runs" | jq -r '.workflow_runs[0].id')

          workflow_run_url="https://github.com/ahmedhassan16/artifacts/actions/runs/$workflow_run_id"
          echo "URL of the most recent workflow run: $workflow_run_url"
         
  clean:
    needs: call-dynamic-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete branch
        uses: ./.github/actions/DeleteBranch
        with:
          destination_repo: 'ahmedhassan16/artifacts'
          api_token: ${{ secrets.PAT_TOKEN }}