name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Main Job Task 1
        run: |
          echo Main Job Task 1

      - name: Main Job Task 2
        run: |
          echo Main Job Task 2

  # SUB_JOB_CALL:
  #   runs-on: ubuntu-latest
  #   extends:
  #     # Reference the job from the separate file
  #     - ./.github/workflows/SubJob.yml