name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  Main_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Main Job Task 1
        run: |
          echo Main Job Task 1

      - name: Main Job Task 2
        run: |
          echo Main Job Task 2

  SUB_JOB_CALL:
    for i in 1 2
    do
      needs: Main_Job
      uses: ./.github/workflows/SubJobx.yml
    done