name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  Main_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Publish to Sharepoint
        uses: obrassard/action-sharepoint-publish@v1.1.1
        with:
          site_url: 'https://mathworks-my.sharepoint.com/personal/ahmedh_mathworks_com'
          library_folder: 'Artifacts/github'
          file_path: 'readme.txt'
          sharepoint_client_id: '4cd89c8c-40ea-4720-a32a-6fc0fea807e7'
          sharepoint_client_secret: 'uomt+FEqalX/WLnR8vY3D1TgWAOWcHDLQCF0kaUIYNc='
          
      - name: Main Job Task 1
        run: |
          echo Main Job Task 1

      - name: Main Job Task 2
        run: |
          echo Main Job Task 2
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .github/workflows/sample.jpeg