name: Sub Job
on:
  workflow_call:

jobs:
  Sub_Job:
    needs: Main_Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps for the job
      - name: Sub Job Task 1
        run: |
          echo empty tasks